spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSLL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.haiyu.blog: info
  file: log/blog-pro.log







